// Reads pre-fetched Coursera metadata from js/certs-data.json (generated by
// scripts/fetch-certs.mjs). Server-side fetch bypasses the browser CORS block
// Coursera's catalog API imposes. Re-run `npm run fetch-certs` to refresh.

const MANIFEST_URL = new URL('./certs-data.json', import.meta.url);

let manifestPromise = null;

async function loadManifest() {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      const res = await fetch(MANIFEST_URL, { cache: 'no-cache' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      return json?.courses || {};
    } catch (err) {
      console.warn('[coursera] certs-data.json unavailable:', err.message,
        '— run `npm run fetch-certs` to generate it.');
      return {};
    }
  })();
  return manifestPromise;
}

function degradedCert(entry) {
  const { slug, credentialId, completedOn, skills } = entry;
  return {
    title: slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    description: '',
    image: null,
    issuer: 'Coursera',
    issuerLogo: null,
    courseUrl: `https://www.coursera.org/learn/${slug}`,
    source: 'coursera',
    credentialId,
    completedOn,
    verifyUrl: `https://coursera.org/verify/${credentialId}`,
    skills: skills || [],
    degraded: true,
  };
}

function mergeCert(entry, manifestEntry) {
  return {
    ...manifestEntry,
    source: 'coursera',
    credentialId: entry.credentialId,
    completedOn: entry.completedOn,
    verifyUrl: `https://coursera.org/verify/${entry.credentialId}`,
    skills: entry.skills?.length ? entry.skills : [],
  };
}

export async function enrichCourseraCert(entry) {
  const manifest = await loadManifest();
  const hit = manifest[entry.slug];
  return hit ? mergeCert(entry, hit) : degradedCert(entry);
}

export async function enrichAllCoursera(entries) {
  if (!entries?.length) return [];
  const manifest = await loadManifest();
  return entries.map((e) => (manifest[e.slug] ? mergeCert(e, manifest[e.slug]) : degradedCert(e)));
}
